services:
  gdbuddy:
    image: ghcr.io/bare-metal-edu/gdbuddy:latest
    environment:
      RUNNER_ORG: https://github.com/allegheny-college-cmpsc-200-fall-2025
      GITHUB_PAT: ${GITHUB_PAT}
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
