services:
  gdbuddy:
    image: ${IMG_NAME}
    environment:
      RUNNER_ORG: https://github.com/${GITHUB_ORG}
      GITHUB_PAT: ${GITHUB_PAT}
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
